export const BASELINE_REGISTRATIONS = [
  {
    id: 'reg-00124',
    registration_code: 'CS26-00124',
    status: 'CONFIRMED',
    created_at: '2026-09-20T10:24:00Z',
    selected_day: 'DAY_1',
    qr_token: 'cs-token-00124',
    participants: {
      name: 'Arjun Kumar',
      email: 'arjun.k@example.com',
      phone: '+91 98765 43210',
      college: 'Vel Tech High Tech College',
      department: 'Computer Science Engineering',
      year: '3rd Year',
    },
    event_registrations: [
      { event_id: 'ev-1', active: true, events: { id: 'ev-1', code: 'CQ', name: 'Code Quest', day: 'DAY_1', event_type: 'TECHNICAL' } },
      { event_id: 'ev-2', active: true, events: { id: 'ev-2', code: 'HK', name: 'Hackathon', day: 'DAY_1', event_type: 'TECHNICAL' } },
    ],
    special_event_registrations: [],
    events: ['Code Quest', 'Hackathon'],
    event_name: 'Code Quest',
  },
  {
    id: 'reg-00125',
    registration_code: 'CS26-00125',
    status: 'CONFIRMED',
    created_at: '2026-09-21T11:15:00Z',
    selected_day: 'DAY_1',
    qr_token: 'cs-token-00125',
    participants: {
      name: 'Sneha R',
      email: 'sneha.r@example.com',
      phone: '+91 98765 43211',
      college: 'SRM Institute of Science',
      department: 'Information Technology',
      year: '2nd Year',
    },
    event_registrations: [
      { event_id: 'ev-3', active: true, events: { id: 'ev-3', code: 'UX', name: 'UI/UX Design', day: 'DAY_1', event_type: 'TECHNICAL' } },
    ],
    special_event_registrations: [],
    events: ['UI/UX Design'],
    event_name: 'UI/UX Design',
  },
  {
    id: 'reg-00126',
    registration_code: 'CS26-00126',
    status: 'PAYMENT_PENDING',
    created_at: '2026-09-22T09:40:00Z',
    selected_day: 'BOTH',
    qr_token: 'cs-token-00126',
    participants: {
      name: 'Vignesh B',
      email: 'vignesh.b@example.com',
      phone: '+91 98765 43212',
      college: 'SSN College of Engineering',
      department: 'Electronics & Communication',
      year: '4th Year',
    },
    event_registrations: [
      { event_id: 'ev-4', active: true, events: { id: 'ev-4', code: 'PP', name: 'Paper Presentation', day: 'DAY_1', event_type: 'TECHNICAL' } },
    ],
    special_event_registrations: [],
    events: ['Paper Presentation'],
    event_name: 'Paper Presentation',
  },
  {
    id: 'reg-00127',
    registration_code: 'CS26-00127',
    status: 'CONFIRMED',
    created_at: '2026-09-23T14:20:00Z',
    selected_day: 'DAY_2',
    qr_token: 'cs-token-00127',
    participants: {
      name: 'Divya Sri',
      email: 'divya.s@example.com',
      phone: '+91 98765 43213',
      college: 'Anna University CEG',
      department: 'Computer Science',
      year: '3rd Year',
    },
    event_registrations: [
      { event_id: 'ev-5', active: true, events: { id: 'ev-5', code: 'TQ', name: 'Tech Quiz', day: 'DAY_2', event_type: 'NON_TECHNICAL' } },
    ],
    special_event_registrations: [],
    events: ['Tech Quiz'],
    event_name: 'Tech Quiz',
  },
  {
    id: 'reg-00128',
    registration_code: 'CS26-00128',
    status: 'CANCELLED',
    created_at: '2026-09-24T16:05:00Z',
    selected_day: 'DAY_1',
    qr_token: 'cs-token-00128',
    participants: {
      name: 'Karthik M',
      email: 'karthik.m@example.com',
      phone: '+91 98765 43214',
      college: 'PSG College of Technology',
      department: 'Mechanical Engineering',
      year: '2nd Year',
    },
    event_registrations: [
      { event_id: 'ev-6', active: true, events: { id: 'ev-6', code: 'PH', name: 'Photography', day: 'DAY_2', event_type: 'NON_TECHNICAL' } },
    ],
    special_event_registrations: [],
    events: ['Photography'],
    event_name: 'Photography',
  },
  {
    id: 'reg-00129',
    registration_code: 'CS26-00129',
    status: 'PAYMENT_PENDING',
    created_at: '2026-09-25T08:50:00Z',
    selected_day: 'BOTH',
    qr_token: 'cs-token-00129',
    participants: {
      name: 'Harini V',
      email: 'harini.v@example.com',
      phone: '+91 98765 43215',
      college: 'Vel Tech High Tech College',
      department: 'Artificial Intelligence & DS',
      year: '3rd Year',
    },
    event_registrations: [
      { event_id: 'ev-2', active: true, events: { id: 'ev-2', code: 'HK', name: 'Hackathon', day: 'DAY_1', event_type: 'TECHNICAL' } },
    ],
    special_event_registrations: [],
    events: ['Hackathon'],
    event_name: 'Hackathon',
  },
];

export const BASELINE_PAYMENTS = [
  {
    id: 'pay-00124',
    registration_id: 'reg-00124',
    amount: 100,
    utr: 'UTR984729104821',
    status: 'VERIFIED',
    submitted_at: '2026-09-20T10:24:00Z',
    screenshot_url: '',
    event_label: 'Code Quest, Hackathon',
    special_event_label: '',
    registrations: {
      registration_code: 'CS26-00124',
      selected_day: 'DAY_1',
      qr_token: 'cs-token-00124',
      participants: {
        name: 'Arjun Kumar',
        email: 'arjun.k@example.com',
        college: 'Vel Tech High Tech College',
        department: 'Computer Science Engineering',
        year: '3rd Year',
      },
      event_registrations: [
        { events: { code: 'CQ', name: 'Code Quest' } },
        { events: { code: 'HK', name: 'Hackathon' } },
      ],
      special_event_registrations: [],
    },
  },
  {
    id: 'pay-00125',
    registration_id: 'reg-00125',
    amount: 100,
    utr: 'UTR819230491823',
    status: 'VERIFIED',
    submitted_at: '2026-09-21T11:15:00Z',
    screenshot_url: '',
    event_label: 'UI/UX Design',
    special_event_label: '',
    registrations: {
      registration_code: 'CS26-00125',
      selected_day: 'DAY_1',
      qr_token: 'cs-token-00125',
      participants: {
        name: 'Sneha R',
        email: 'sneha.r@example.com',
        college: 'SRM Institute of Science',
        department: 'Information Technology',
        year: '2nd Year',
      },
      event_registrations: [
        { events: { code: 'UX', name: 'UI/UX Design' } },
      ],
      special_event_registrations: [],
    },
  },
  {
    id: 'pay-00126',
    registration_id: 'reg-00126',
    amount: 200,
    utr: 'UTR492019482019',
    status: 'UNDER_REVIEW',
    submitted_at: '2026-09-22T09:40:00Z',
    screenshot_url: '',
    event_label: 'Paper Presentation',
    special_event_label: '',
    registrations: {
      registration_code: 'CS26-00126',
      selected_day: 'BOTH',
      qr_token: 'cs-token-00126',
      participants: {
        name: 'Vignesh B',
        email: 'vignesh.b@example.com',
        college: 'SSN College of Engineering',
        department: 'Electronics & Communication',
        year: '4th Year',
      },
      event_registrations: [
        { events: { code: 'PP', name: 'Paper Presentation' } },
      ],
      special_event_registrations: [],
    },
  },
  {
    id: 'pay-00127',
    registration_id: 'reg-00127',
    amount: 100,
    utr: 'UTR772819304921',
    status: 'VERIFIED',
    submitted_at: '2026-09-23T14:20:00Z',
    screenshot_url: '',
    event_label: 'Tech Quiz',
    special_event_label: '',
    registrations: {
      registration_code: 'CS26-00127',
      selected_day: 'DAY_2',
      qr_token: 'cs-token-00127',
      participants: {
        name: 'Divya Sri',
        email: 'divya.s@example.com',
        college: 'Anna University CEG',
        department: 'Computer Science',
        year: '3rd Year',
      },
      event_registrations: [
        { events: { code: 'TQ', name: 'Tech Quiz' } },
      ],
      special_event_registrations: [],
    },
  },
  {
    id: 'pay-00128',
    registration_id: 'reg-00128',
    amount: 100,
    utr: 'UTR192837465019',
    status: 'REJECTED',
    rejection_reason: 'Unclear transaction reference in receipt',
    submitted_at: '2026-09-24T16:05:00Z',
    screenshot_url: '',
    event_label: 'Photography',
    special_event_label: '',
    registrations: {
      registration_code: 'CS26-00128',
      selected_day: 'DAY_1',
      qr_token: 'cs-token-00128',
      participants: {
        name: 'Karthik M',
        email: 'karthik.m@example.com',
        college: 'PSG College of Technology',
        department: 'Mechanical Engineering',
        year: '2nd Year',
      },
      event_registrations: [
        { events: { code: 'PH', name: 'Photography' } },
      ],
      special_event_registrations: [],
    },
  },
  {
    id: 'pay-00129',
    registration_id: 'reg-00129',
    amount: 200,
    utr: 'UTR998877665544',
    status: 'UNDER_REVIEW',
    submitted_at: '2026-09-25T08:50:00Z',
    screenshot_url: '',
    event_label: 'Hackathon',
    special_event_label: '',
    registrations: {
      registration_code: 'CS26-00129',
      selected_day: 'BOTH',
      qr_token: 'cs-token-00129',
      participants: {
        name: 'Harini V',
        email: 'harini.v@example.com',
        college: 'Vel Tech High Tech College',
        department: 'Artificial Intelligence & DS',
        year: '3rd Year',
      },
      event_registrations: [
        { events: { code: 'HK', name: 'Hackathon' } },
      ],
      special_event_registrations: [],
    },
  },
];
